name: Run e2e test for check safe apps liveness
on:
  pull_request:
  schedule:
    # At 9:00 on every day-of-week from Monday through Friday
    - cron: '0 9 * * 1-5'
env:
  PUPPETEER_EXEC_PATH: 'google-chrome-stable'
jobs:
  runE2eTests:
    name: Run e2e testing safe apps liveness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Create folder
        run: mkdir -p screenshots
      - name: Test Code
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
          TESTING_ENV: 'prod'
          NETWORK_NAME: 'mainnet'
          NETWORK_ADDRESS_PREFIX: 'eth'
          TESTING_SAFE_ADDRESS: ${{ secrets.TESTING_SAFE_ADDRESS }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          args: yarn test working_apps
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots/*
